import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from 'react'
import Auth from './Components/Auth'
import {useAuthState} from "react-firebase-hooks/auth"

import firebase, {auth, db, provider} from '../firebase/clientApp'
// import firebase, {auth, db, provider} from '../firebase/clientApp'

// import { auth } from '../firebase/clientApp'

// console.log(auth)



export default function Home() {
  
  
  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(true)
  
  
  const [user, userAuthIsLoading, userAuthError] = useAuthState(auth)
  console.log(`Loading: ${userAuthIsLoading} || Current user: ${user}`)
  // console.log(user)
  
  // useEffect(() => {
  //   setLoading(true)

  //   // fetch('/api/hello').then((res) => res.json() )
  //   //   .then((x) => {
  //   //     setData(x)
  //   //     setLoading(false)
  //   //   })

  //   fetch('/api/hello').then((response) => {
  //     // console.log(...response.headers)
  //     // console.log(response)
  //     response.json().then((x) => {
  //       // console.log(x)
  //       setData(x)
  //       setLoading(false)
  //     })
  //   })

  // }, [])


  return (
    <div className={styles.container}>
      <Head>
        <title>xkTransfer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon"  href="favicon.ico?v=1.1" />
      </Head>
      {
        user &&

        <nav className={styles.nav}>
            {user.displayName}
             _
            {user.email}
            _
            {<Image src={user.photoURL} 
              className={styles.userIcon}
              alt="User Photo" 
              width={'100%'} 
              height={'100%'} />} 
              
        </nav>
      }

      <main>
        <h1>
          XKTransfer
        </h1>
        <h1>
          {data ? data.name : ""} 
        </h1>
        {/* <form enctype="multipart/form-data" method="POST" action="/api/fileanalyse"> */}
        <form method="POST" action="/api/handlefiles">
            <input id="inputfield" type="file" name="upfile" />
            <input id="button" type="submit" value="Upload" />
        </form>

        
      </main>

      <footer className={styles.footer}>
      
        <Auth />
        {/* {user} */}

      </footer>
    </div>
  )
}
