import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import React, {useState, useEffect} from 'react'
import Auth from './Components/Auth'


export default function Home() {
  

  const [data, setData] = useState(null)
  const [isLoading, setLoading] = useState(true)
  
  // useEffect(() => {
  //   setLoading(true)

  //   // fetch('/api/hello').then((res) => res.json() )
  //   //   .then((x) => {
  //   //     setData(x)
  //   //     setLoading(false)
  //   //   })

  //   fetch('/api/hello').then((response) => {
  //     // console.log(...response.headers)
  //     // console.log(response)
  //     response.json().then((x) => {
  //       // console.log(x)
  //       setData(x)
  //       setLoading(false)
  //     })
  //   })

  // }, [])

  function logSomething() {
    console.log('function called')
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>xkTransfer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon"  href="favicon.ico?v=1.1" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          XKTransfer
        </h1>

        <h1>
          {data ? data.name : ""} 
        </h1>

        <Auth />

        <button
          onClick={logSomething}
        >
          button on index
        </button>



        
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
